source 'http://rubygems.org'

gem 'rails', '3.1.1'

gem 'sqlite3-ruby', '1.3.3', :require => 'sqlite3'

gem 'mocha', :group => :test

gem "rmagick"
gem "carrierwave"

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
